// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA4c2nQrJM4XkfWUB397x8Uk63N3ugl6Y',
    appId: '1:977838903383:web:4e98ed74bcbec1158e5312',
    messagingSenderId: '977838903383',
    projectId: 'gastrobot-5bc84',
    authDomain: 'gastrobot-5bc84.firebaseapp.com',
    storageBucket: 'gastrobot-5bc84.firebasestorage.app',
    measurementId: 'G-FN97QSKL8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVnHE7UEIX8XatKlTd7wKYhRjLpWcczFU',
    appId: '1:977838903383:android:4c8b4157d638a2c18e5312',
    messagingSenderId: '977838903383',
    projectId: 'gastrobot-5bc84',
    storageBucket: 'gastrobot-5bc84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz9WEUyxQ7941Ggwm81vMMJcR1YJUMB38',
    appId: '1:977838903383:ios:21380bfde587a1188e5312',
    messagingSenderId: '977838903383',
    projectId: 'gastrobot-5bc84',
    storageBucket: 'gastrobot-5bc84.firebasestorage.app',
    iosBundleId: 'eu.brrm.gastrocrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz9WEUyxQ7941Ggwm81vMMJcR1YJUMB38',
    appId: '1:977838903383:ios:21380bfde587a1188e5312',
    messagingSenderId: '977838903383',
    projectId: 'gastrobot-5bc84',
    storageBucket: 'gastrobot-5bc84.firebasestorage.app',
    iosBundleId: 'eu.brrm.gastrocrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqvcVEyXA4aCBaLUExUz-GmZgePUFjJCw',
    appId: '1:977838903383:web:8514c9e7186e909f8e5312',
    messagingSenderId: '977838903383',
    projectId: 'gastrobot-5bc84',
    authDomain: 'gastrobot-5bc84.firebaseapp.com',
    storageBucket: 'gastrobot-5bc84.firebasestorage.app',
    measurementId: 'G-6T32DC288X',
  );

}